name: CI-OS2

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.github/FUNDING.yml'

  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.github/FUNDING.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - os2_emxomf: '-Dos2_emxomf=true'
            cross_file: $OS2EMX_MESON_CROSS_FILE_OMF

          - os2_emxomf: '-Dos2_emxomf=false'
            cross_file: $OS2EMX_MESON_CROSS_FILE_AOUT

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup cross-os2emx
        uses: komh/setup-cross-os2emx@v1
        with:
          version: 1.3.1

      - name: Setup meson build
        run: |
          mkdir build
          meson setup build \
            --prefix=/@unixroot/usr --default-library=both \
            ${{ matrix.os2_emxomf }} --cross-file=${{ matrix.cross_file }}

      - name: Build
        run: |
          ninja -C build

      - name: Install
        run: |
          meson install -C build --destdir=${{ github.workspace }}/dav1d
